src/main/java/com/javaproject/musicbox/entities/Item.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javaproject.musicbox.entities;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

/**
 *
 * @author Danny
 */
@Entity
@Table(name = "item")
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(discriminatorType = DiscriminatorType.STRING, name = "item_type")
public abstract class Item implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "item_id")
    private int itemId;

    @Column(name = "item_type")
    private String itemType;

    @Column(name = "list_price")
    private double listPrice;

    @Column(name = "cost_price")
    private double costPrice;

    @Column(name = "sales_price")
    private double salesPrice;

    @Column(name = "name")
    private String name;

    @Column(name = "picture_path")
    private String picturePath;

    @Column(name = "date_added")
    private Date dateAdded;

    @Column(name = "date_removed")
    private Date dateRemoved;

    @JoinTable(name = "category_item", joinColumns = {
        @JoinColumn(name = "item_id", referencedColumnName = "item_id")}, inverseJoinColumns = {
        @JoinColumn(name = "category_id", referencedColumnName = "category_id")})
    @ManyToMany
    private List<Category> categoryList;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "itemId", fetch = FetchType.EAGER)
    private List<Review> reviewList;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "item")
    private List<OrderItem> orderItems;

    public Item() {
        reviewList = new ArrayList<>();
        orderItems = new ArrayList<>();
        categoryList = new ArrayList<>();
    }

    public Item(int itemId, String itemType) {
        this.itemId = itemId;
        this.itemType = itemType;
    }

    public Item(int itemId, double listPrice, double costPrice, String name, Date dateAdded) {
        this.itemId = itemId;
        this.listPrice = listPrice;
        this.costPrice = costPrice;
        this.name = name;
        this.dateAdded = dateAdded;
    }

    public List<String> getListOf5() {
        List<String> i = new ArrayList<>();
        i.add("1");
        i.add("2");
        i.add("3");
        i.add("4");
        i.add("5");

        return i;
    }

    public int getItemId() {
        return itemId;
    }

    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    public String getItemType() {
        return itemType;
    }

    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    public double getListPrice() {
        return listPrice;
    }

    public void setListPrice(double listPrice) {
        this.listPrice = listPrice;
    }

    public double getCostPrice() {
        return costPrice;
    }

    public void setCostPrice(double costPrice) {
        this.costPrice = costPrice;
    }

    public double getSalePrice() {
        return salesPrice;
    }

    public void setSalePrice(double sp) {
        this.salesPrice = sp;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPicturePath() {
        if(picturePath == null){
            picturePath  = "default.png";
        }
        
        return picturePath;
    }

    public void setPicturePath(String picturePath) {
        if(picturePath == null){
            this.picturePath  = "default.png";
        }
        
        this.picturePath = picturePath;
    }

    public Date getDateAdded() {
        return dateAdded;
    }

    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    public Date getDateRemoved() {
        return dateRemoved;
    }

    public void setDateRemoved(Date dateRemoved) {
        this.dateRemoved = dateRemoved;
    }

    public List<Category> getCategoryList() {
        return categoryList;
    }

    public void setCategoryList(List<Category> categoryList) {
        this.categoryList = categoryList;
    }

    public List<Review> getReviewList() {
        return reviewList;
    }

    public void setReviewList(List<Review> reviewList) {
        this.reviewList = reviewList;
    }

    public int getAverageReview() {
        double total = 0;
        int count = 0;
        for (Review r : getReviewList()) {
            total += (r.getStarRating() * 1.0);
            count++;
        }

        return (int) Math.round(total / count);
    }

    public int getReviewQuantity() {
        return getReviewList().size();
    }

    public void addReview(Review review) {
        reviewList.add(review);
    }

    public List<OrderItem> getOrderItems() {
        return orderItems;
    }

    public void setOrderItems(List<OrderItem> orderItems) {
        this.orderItems = orderItems;
    }

    public void addOrderItem(OrderItem orderItem) {
        this.orderItems.add(orderItem);
    }

    public int countItem() {
        return this.getOrderItems().size();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Item item = (Item) o;
        
        if(!item.name.equals(name)){
            return false;
        }
        
        if(!item.itemType.equals(itemType)){
           return false; 
        }
        
        return true;
    }

    @Override
    public int hashCode() {
        return Objects.hash(itemId);
    }

    @Override
    public String toString() {
        return "Item{"
                + "itemId=" + itemId
                + "itemType=" + itemType
                + ", listPrice=" + listPrice
                + ", costPrice=" + costPrice
                + ", salesPrice=" + salesPrice
                + ", name='" + name + '\''
                + ", picturePath='" + picturePath + '\''
                + ", dateAdded=" + dateAdded
                + ", dateRemoved=" + dateRemoved
                + ", categoryList=" + categoryList
                + ", reviewList=" + reviewList
                + '}';
    }
}

src/main/webapp/resources/components/ItemDisplay.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:fn="http://xmlns.jcp.org/jsp/jstl/functions"
      xmlns:jsf="http://xmlns.jcp.org/jsf">

    <!-- INTERFACE -->
    <cc:interface>
        <cc:attribute name="item"/>
    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
        <div class="unit" id="#{cc.attrs.item.itemId}">
            <h:panelGroup layout="block" class="album_display">

                <!-- ITEM IMAGE -->
                <figure class="img_container">
                    <h:link outcome="/storefront/pages/public/itemDetails">
                        <f:param name="id" value="#{cc.attrs.item.itemId}"/>
                        <h:graphicImage class="fit_cover" alt="track image" value="/images/#{cc.attrs.item.picturePath}"/>
                    </h:link>
                </figure>

                <!-- ITEM NAME -->
                <h:link value="#{cc.attrs.item.name}" class="album_title_link" outcome="/storefront/pages/public/itemDetails">
                    <f:param name="id" value="#{cc.attrs.item.itemId}"/>
                </h:link>

                <p id="artist">
                    <!--IF ALBUM-->
                    <h:outputText value="#{cc.attrs.item.artist.name}" rendered="${cc.attrs.item.itemType == 'album'}"/>

                    <!--IF TRACK-->
                    <ui:repeat value="#{cc.attrs.item.artistList}" var="artist" size="1" rendered="${cc.attrs.item.itemType == 'track'}">
                        <h:outputText value="#{artist.name}"  />
                    </ui:repeat>
                </p>


                <!-- REVIEW STARS -->
                <div class="review_section">
                    <ui:repeat value="#{cc.attrs.item.listOf5}" var="star" size="#{cc.attrs.item.averageReview}" rendered="#{cc.attrs.item.averageReview ne 0}">
                        <h:graphicImage class="basic_star" value="/resources/images/review_star_yellow.svg"/>
                    </ui:repeat>
                    <ui:repeat value="#{cc.attrs.item.listOf5}" var="star" size="#{5 - cc.attrs.item.averageReview}" rendered="#{cc.attrs.item.averageReview ne 5}">
                        <h:graphicImage class="basic_star" value="/resources/images/review_star_blank.svg"/>                    
                    </ui:repeat>
                    <span class="review_count">
                        (#{cc.attrs.item.reviewQuantity})
                    </span>
                </div>

                <!-- ITEM PRICE -->
                <h:form rendered="#{cc.attrs.item.salePrice eq 0.0}">
                    <div class="prices">
                        <p id="list_price" class="price">#{cc.attrs.item.listPrice}</p>
                    </div>
                </h:form>

                <h:form rendered="#{cc.attrs.item.salePrice ne 0.0}">
                    <div class="prices">
                        <p id="sales_price" class="price">#{cc.attrs.item.salePrice}</p>
                        <p id="list_price" class="price cancelled_price">#{cc.attrs.item.listPrice}</p>
                    </div>
                </h:form>
                <!-- ITEM INFORMATION BASED ON ITEM TYPE -->
                <p id="artist">#{cc.attrs.item.itemType}</p>

                <!-- ADD TO CART BUTTON -->
                <h:panelGroup layout="block" class="button_group">
                    <h:form>
                        <h:commandButton class="button add_to_cart_button"
                                         action="#{shoppingCartBean.addItemToCart(cc.attrs.item.itemId)}"
                                         value="#{msg.addToCart}"
                                         >
                            <f:ajax render="cart_info" />
                        </h:commandButton>
                    </h:form>
                </h:panelGroup>
            </h:panelGroup>
        </div>
    </cc:implementation>
</html>