src/main/java/com/javaproject/musicbox/managedbeans/admin/AdEditorBean.java
package com.javaproject.musicbox.managedbeans.admin;

import com.javaproject.musicbox.services.AdService;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;

@Named
@ViewScoped
public class AdEditorBean implements Serializable {
    @Inject
    private AdService adDAO;

    private String imageURL;
    private String websiteURL;

    /**
     * Creates a new Ad from manager input.
     * @return the outcome of the create action (redirect back to ad list page)
     */
    public String createNewAd(){
        //Call DAO create method
        adDAO.createAd(this.imageURL, this.websiteURL);

        //Redirect back to the ad list page
        return "/storefront/pages/admin/adList?faces-redirect=true";
    }

    public String getImageURL() {
        return imageURL;
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    public String getWebsiteURL() {
        return websiteURL;
    }

    public void setWebsiteURL(String websiteURL) {
        this.websiteURL = websiteURL;
    }
}

src/main/java/com/javaproject/musicbox/managedbeans/admin/AdListBean.java
package com.javaproject.musicbox.managedbeans.admin;

import com.javaproject.musicbox.entities.Ad;
import com.javaproject.musicbox.services.AdService;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.List;

@Named
@RequestScoped
public class AdListBean {
    @Inject
    private AdService adDAO;

    private List<Ad> ads;

    @PostConstruct
    private void init(){
        ads = adDAO.findAll();
    }

    /**
     * Calls the DAO method to activate an Ad and updates the page.
     * @param adID which AD to activate
     * @param position left(1) or right(2) ad
     */
    public void activateAd(int adID, int position){
        adDAO.activateAd(adID, position);
        //Update
        ads = adDAO.findAll();
    }

    public List<Ad> getAds() {
        return ads;
    }

    public void setAds(List<Ad> ads) {
        this.ads = ads;
    }
}

src/main/java/com/javaproject/musicbox/managedbeans/admin/ArtistEditorBean.java
package com.javaproject.musicbox.managedbeans.admin;

import com.javaproject.musicbox.services.ArtistService;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author Danny
 */
@Named
@RequestScoped
public class ArtistEditorBean {
    @Inject
    private ArtistService artistService;
    
    private String name;

    
    
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public String createArtist(){
        artistService.createArtist(name);
        
        return "/storefront/pages/admin/inventoryList.xhtml?faces-redirect=true&amp;editSuccess=true";
    }
    
}

src/main/java/com/javaproject/musicbox/managedbeans/admin/ClientEditorBean.java
package com.javaproject.musicbox.managedbeans.admin;

import com.javaproject.musicbox.entities.User;
import com.javaproject.musicbox.services.UserService;
import com.javaproject.musicbox.util.ContextUtilities;
import com.javaproject.musicbox.util.EncryptionUtilities;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.IOException;
import java.io.Serializable;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;

@Named
@ViewScoped
public class ClientEditorBean implements Serializable {
    @Inject
    private UserService userDAO;

    private int userID;
    private User user;

    @PostConstruct
    private void init(){
        user = new User();
    }

    /**
     * Set the User instance of the current user whose registration info we want to edit. In the case where the user
     * is not found, the page redirects to 404.
     * @throws IOException
     */
    public void findUser() throws IOException {
        if(userID <= 0){
            ContextUtilities.redirectTo404();
            return;
        }

        user = userDAO.findById(userID);

        if(user == null){
            ContextUtilities.redirectTo404();
        }
    }

    /**
     * Saves the changes made to the user by calling the appropriate User Service method.
     * @return the outcome of the action (redirect back to client/user list)
     */
    public String saveUserInfo() throws InvalidKeySpecException, NoSuchAlgorithmException {
        //If a new password has been set for the user
        if(user.getPassword() != null && !user.getPassword().isEmpty()) {
            // Generate salt & hash from password
            String salt = EncryptionUtilities.generateSalt();
            byte[] hash = EncryptionUtilities.generateHash(user.getPassword(), salt);

            // Store the generated hash and salt in the user
            user.setHash(hash);
            user.setSalt(salt);
        }

        userDAO.update(user);

        //Redirect back to client/user list page
        return "/storefront/pages/admin/clientList?faces-redirect=true";
    }

    /**
     * Validates the email if the address has been modified by the manager only.
     * @param context Faces context
     * @param component the UIComponent to set as invalid
     * @param value the email address
     */
    public void validateEmail(FacesContext context, UIComponent component, Object value) {
        String email = (String) value;
        //First check if user email has been changed
        if(!email.equals(user.getEmail())) {

            // Check if the email address might be valid using a regex pattern
            boolean isValidEmail = email.matches("^([a-zA-Z0-9_\\-.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(]?)$");
            if (!isValidEmail) {
                ((UIInput) component).setValid(false);
                FacesMessage msg = new FacesMessage("Invalid email address");
                context.addMessage(component.getClientId(context), msg);
            } else {
                // If the email is valid, check if the email is already used
                boolean emailUsed = userDAO.checkEmailUsed(email);
                if (emailUsed) {
                    ((UIInput) component).setValid(false);
                    FacesMessage msg = new FacesMessage("Email is already in use");
                    context.addMessage(component.getClientId(context), msg);
                }
            }
        }
    }

    public int getUserID() {
        return userID;
    }

    public void setUserID(int userID) {
        this.userID = userID;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}

src/main/java/com/javaproject/musicbox/managedbeans/admin/GenreEditorBean.java
package com.javaproject.musicbox.managedbeans.admin;

import com.javaproject.musicbox.entities.Category;
import com.javaproject.musicbox.services.CategoryService;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author Danny
 */
@Named
@RequestScoped
public class GenreEditorBean {
    
    @Inject 
    private CategoryService categoryService;
    
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public String createGenre(){
        categoryService.createCategory(name);
        
        return "/storefront/pages/admin/inventoryList.xhtml?faces-redirect=true&amp;editSuccess=true";
    }
}

src/main/java/com/javaproject/musicbox/managedbeans/storefront/admin/ReportsBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javaproject.musicbox.managedbeans.storefront.admin;

import com.javaproject.musicbox.entities.Album;
import com.javaproject.musicbox.entities.Artist;
import com.javaproject.musicbox.entities.Item;
import com.javaproject.musicbox.entities.Order;
import com.javaproject.musicbox.entities.OrderItem;
import com.javaproject.musicbox.entities.Track;
import com.javaproject.musicbox.entities.User;
import com.javaproject.musicbox.services.ItemService;
import com.javaproject.musicbox.services.UserService;
import com.javaproject.musicbox.services.admin.ReportsService;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author Lara
 */
@Named
@RequestScoped
public class ReportsBean implements Serializable {

    @Inject
    ReportsService rs;
    @Inject
    UserService us;
    @Inject
    ItemService is;
    private List<Order> orders;
    private double totalSales;
    private Date from, to;
    private User user;
    private Artist artist;
    private Item track, album;
    private List<Item> distinctItems, topSellersTrack, topSellersAlbum, zeroSellers;
    private List<User> topSellerUsers, zeroSellerUsers;
    private String artistId, clientId, trackId, albumId;

    @PostConstruct
    private void init() {
        /**
         * This is temp due to a bug
         */

        artistId = "1";
        albumId = "1";
        trackId = "70";
        clientId = "2";
        artist = rs.getAllArtists().get(47 - 1);
        track = is.findById(70);
        album = is.findById(1);
        user = us.findById(2);
        /**
         * ************************************
         */
        from = new Date();
        to = new Date();
        //get all orders according to date
        orders = rs.getAllOrderedItems(from, to);
        //temp list
        List<Item> items = new ArrayList<>();
        //create a disctinct list of items that are in the order table
        orders.forEach(order -> order.getOrderItems().forEach(orderItem -> items.add(orderItem.getItem())));
        distinctItems = items.stream().distinct().collect(Collectors.toList());
        //total sales for the disctinct items from given dates
        totalSales = Math.round(rs.getTotalCost(new Date(), new Date()) * 100.0) / 100.0;
        //top track and album sellers
        topSellersTrack = distinctItems.stream().filter(item -> item.getItemType().equals("track")).sorted(Comparator.comparing(Item::countItem).reversed())
                .collect(Collectors.toList());
        topSellersAlbum = distinctItems.stream().filter(item -> item.getItemType().equals("album")).sorted(Comparator.comparing(Item::countItem).reversed())
                .collect(Collectors.toList());
        //filter zero sellers items
        zeroSellers = rs.getAllItems().stream().filter(item -> item.countItem() == 0).collect(Collectors.toList());
        //filter top buyers
        topSellerUsers = rs.getAllUsers().stream().filter(user -> user.getTotalUserPayed() > 0).sorted(Comparator.comparing(User::getTotalUserPayed).reversed()).collect(Collectors.toList());
        //filter zero items
        zeroSellerUsers = rs.getAllUsers().stream().filter(user -> user.getTotalUserPayed() == 0).sorted(Comparator.comparing(User::getTotalUserPayed).reversed()).collect(Collectors.toList());
    }

    public List<Item> getDistinctItems() {
        return distinctItems;
    }

    public void setDistinctItems(List<Item> distinctItems) {
        this.distinctItems = distinctItems;
    }

    public List<Order> getOrders() {
        return orders;
    }

    public void setOrders(List<Order> orders) {
        this.orders = orders;
    }

    public double getTotalSales() {
        return totalSales;
    }

    public void setTotalSales(double totalSales) {
        this.totalSales = totalSales;
    }

    public Date getFrom() {
        return from;
    }

    public void setFrom(Date from) {
        this.from = from;
    }

    public Date getTo() {
        return to;
    }

    public void setTo(Date to) {
        this.to = to;
    }

    public List<User> getUsers() {
        return rs.getAllUsers();
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Artist getArtist() {
        return artist;
    }

    public void setArtist(Artist artist) {
        this.artist = artist;
    }

    public Item getTrack() {
        return track;
    }

    public void setTrack(Item track) {
        this.track = track;
    }

    public Item getAlbum() {
        return album;
    }

    public void setAlbum(Item album) {
        this.album = album;
    }

    public List<Order> ordersPerAlbum() {
        return rs.getOrdersForItem(album.getItemId());
    }

    public List<Item> getTopSellersTrack() {
        return topSellersTrack;
    }

    public void setTopSellersTrack(List<Item> topSellersTrack) {
        this.topSellersTrack = topSellersTrack;
    }

    public List<Item> getTopSellersAlbum() {
        return topSellersAlbum;
    }

    public void setTopSellersAlbum(List<Item> topSellersAlbum) {
        this.topSellersAlbum = topSellersAlbum;
    }

    public List<Item> getZeroSellers() {
        return zeroSellers;
    }

    public void setZeroSellers(List<Item> zeroSellers) {
        this.zeroSellers = zeroSellers;
    }

    public List<User> getTopSellerUsers() {
        return topSellerUsers;
    }

    public void setTopSellerUsers(List<User> topSellerUsers) {
        this.topSellerUsers = topSellerUsers;
    }

    public List<User> getZeroSellerUsers() {
        return zeroSellerUsers;
    }

    public void setZeroSellerUsers(List<User> zeroSellerUsers) {
        this.zeroSellerUsers = zeroSellerUsers;
    }

    public String getArtistId() {
        return artistId;
    }

    public void setArtistId(String artistId) {
        this.artistId = artistId;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getTrackId() {
        return trackId;
    }

    public void setTrackId(String trackId) {
        this.trackId = trackId;
    }

    public String getAlbumId() {
        return albumId;
    }

    public void setAlbumId(String albumId) {
        this.albumId = albumId;
    }

    /**
     * Get all the items the user purchased
     *
     * @return
     */
    public List<Item> getUserItems() {
        return rs.getAllUsersItem(user);
    }

    /**
     * Get the total amount of money the user payed for all the items they
     * ordered
     *
     * @return
     */
    public double getTotalUserPayed() {
        return Math.round(rs.getTotalUserPayed(user) * 100.0) / 100.0;
    }

    /**
     * Get all artists
     *
     * @return
     */
    public List<Artist> getArtists() {
        return rs.getAllArtists();
    }

    /**
     * Count how many times the items was ordered
     *
     * @param i
     * @return
     */
    public int countItem(Item i) {
        return i.getOrderItems().size();
    }

    /**
     * Get all items within a given type
     *
     * @param type
     * @return
     */
    public List<Item> getAllItems(String type) {
        return rs.getAllItemsWithType(type);
    }

    /**
     * Get total sales per album
     *
     * @return
     */
    public double totalSalesPerAlbum() {
        return Math.round(countItem(album) * (album.getListPrice() - album.getSalePrice()) * 100.0) / 100.0;
    }

    /**
     * Get total sales per track
     *
     * @return
     */
    public double totalSalesPerTrack() {
        return Math.round(countItem(track) * (track.getListPrice() - track.getSalePrice()) * 100.0) / 100.0;
    }

    /**
     * Get all orders that contain a given album
     *
     * @return
     */
    public List<OrderItem> getAllTrackOrders() {
        return is.findById(track.getItemId()).getOrderItems();
    }

    /**
     * Get all orders that contain a given track
     *
     * @return
     */
    public List<OrderItem> getAllAlbumOrders() {
        return is.findById(album.getItemId()).getOrderItems();
    }

    /**
     * Calculate the total money gained by an artist from albums
     *
     * @return
     */
    public double totalPayedArtistAlbum() {
        double gain = 0;
        //all the albums of the artist that were sold 
        for (Album a : artist.getAlbumCollection()) {
            gain += a.countItem() * a.getListPrice() - a.getSalePrice(); //to add
        }
        return gain;
    }

    /**
     * Calculate the total money gained by an artist from track
     *
     * @return
     */
    public double totalPayedArtistTrack() {
        double gain = 0;
        //all the albums of the artist that were sold 
        for (Track a : artist.getTrackCollection()) {
            gain += a.countItem() * a.getListPrice() - a.getSalePrice(); //to add
        }
        return gain;
    }

    public void submitArtist() {
        artist = rs.getAllArtists().get(Integer.parseInt(artistId) - 1);
    }

    public void submitClient() {
        user = us.findById(Integer.parseInt(clientId));
    }

    public void submitTrack() {
        track = is.findById(Integer.parseInt(trackId));
    }

    public void submitAlbum() {
        album = is.findById(Integer.parseInt(albumId));
    }

    public void filterByDate() {
      
    }
}

src/main/webapp/storefront/pages/admin/adList.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<ui:composition template="/storefront/templates/managerTemplate.xhtml">
    <ui:define name="metadata">
        <f:metadata>

            <!-- SET THIS PAGE AS ACTIVE -->
            <f:viewAction action="#{navBean.setActivePage('ads')}"/>

        </f:metadata>
    </ui:define>
    <ui:define name="content">
        <h:panelGroup layout="block" class="admin_data">
            <!-- BUTTON TO CREATE A NEW AD -->
            <h:panelGroup layout="block" class="admin_data__toolbar">
                <h:link styleClass="button button-small button--dark button--small"
                        value="Create a new advertisement"
                        outcome="/storefront/pages/admin/adEditor"/>
            </h:panelGroup>

            <!-- DATATABLE -->
            <h:panelGroup id="adList" layout="block" class="admin_data__table-wrapper js-dataTable-wrapper">
                <h:dataTable id="adListTable" styleClass="dataTable hover stripe order-column row-border"
                             value="#{adListBean.ads}"
                             var="ad">
                    <!-- AD ID -->
                    <h:column id="idCol">
                        <f:facet name="header">Ad ID</f:facet>
                        <h:outputText value="#{ad.id}"/>
                    </h:column>
                    <!-- IMAGE URL -->
                    <h:column id="imgUrlCol">
                        <f:facet name="header">Image URL</f:facet>
                        <h:outputText value="#{ad.imageURL}"/>
                    </h:column>
                    <!-- WEBSITE URL -->
                    <h:column id="websiteUrlCol">
                        <f:facet name="header">Website URL</f:facet>
                        <h:outputText value="#{ad.websiteURL}"/>
                    </h:column>
                    <!-- LEFT AD ACTIVE STATUS -->
                    <h:column id="leftAdActiveStatusCol">
                        <f:facet name="header">Left Ad Active Status</f:facet>
                        <h:outputText value="#{ad.activeAsAd1 ? 'Active' : 'Inactive'}"/>
                    </h:column>
                    <!-- RIGHT AD ACTIVE STATUS -->
                    <h:column id="RightAdActiveStatusCol">
                        <f:facet name="header">Right Ad Active Status</f:facet>
                        <h:outputText value="#{ad.activeAsAd2 ? 'Active' : 'Inactive'}"/>
                    </h:column>

                    <!-- SET AS ACTIVE ACTION BUTTONs -->
                    <h:column id="actionCol">
                        <f:facet name="header">Modify Status</f:facet>
                        <h:panelGroup layout="block" id="adActionGroup" styleClass="admin_data__actions">
                            <h:form id="activateAsLeftAd">
                                <h:commandButton value="Set as left ad"
                                                 action="#{adListBean.activateAd(ad.id, 1)}"
                                                 styleClass="button"/>
                            </h:form>
                            <h:form id="activeAsRightAd">
                                <h:commandButton value="Set as right ad"
                                                 action="#{adListBean.activateAd(ad.id, 2)}"
                                                 styleClass="button"/>
                            </h:form>
                        </h:panelGroup>
                    </h:column>
                </h:dataTable>
            </h:panelGroup>
        </h:panelGroup>
    </ui:define>
</ui:composition>
</html>

src/main/webapp/storefront/pages/admin/artistEditor.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">>
<ui:composition template="/storefront/templates/managerTemplate.xhtml">
    <ui:define name="metadata">
        <f:metadata>

            <!-- SET THIS PAGE AS ACTIVE -->
            <f:viewAction action="#{navBean.setActivePage('artist')}"/>

        </f:metadata>
    </ui:define>
    <ui:define name="content">
        <h:form id="createNewAdForm" styleClass="admin_data__form">
            <h:panelGroup layout="block" styleClass="input">
                <h:outputLabel styleClass="input__label" for="Name" value="Name"/>
                <h:inputText id="Name" styleClass="input__field" value="#{artistEditorBean.name}"/>
            </h:panelGroup>
            
            <h:commandButton styleClass="button button-small button--dark button--small" value="Create Artist"
                             action="#{artistEditorBean.createArtist()}"/>
        </h:form>
    </ui:define>

</ui:composition>
</html>

src/main/webapp/storefront/pages/admin/clientList.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<ui:composition template="/storefront/templates/managerTemplate.xhtml">
    <ui:define name="metadata">
        <f:metadata>

            <!-- SET THIS PAGE AS ACTIVE -->
            <f:viewAction action="#{navBean.setActivePage('clients')}"/>

        </f:metadata>
    </ui:define>
    <ui:define name="content">
        <h:panelGroup layout="block" class="admin_data">
            <!-- DATATABLE -->
            <h:panelGroup id="clientList" layout="block" class="admin_data__table-wrapper js-dataTable-wrapper">
                <h:dataTable id="clientListTable" styleClass="dataTable hover stripe order-column row-border"
                             value="#{clientListBean.users}"
                             var="user">
                    <!-- CLIENT ID -->
                    <h:column id="idCol">
                        <f:facet name="header">Client ID</f:facet>
                        <h:outputText value="#{user.userId}"/>
                    </h:column>
                    <!-- EMAIL -->
                    <h:column id="questionCol">
                        <f:facet name="header">Email</f:facet>
                        <h:outputText value="#{user.email}"/>
                    </h:column>
                    <!-- FNANE -->
                    <h:column id="fnameCol">
                        <f:facet name="header">First name</f:facet>
                        <h:outputText value="#{user.firstName}"/>
                    </h:column>
                    <!-- LNAME -->
                    <h:column id="lnameCol">
                        <f:facet name="header">Last name</f:facet>
                        <h:outputText value="#{user.lastName}"/>
                    </h:column>
                    <!-- ADDR1 -->
                    <h:column id="addr1Col">
                        <f:facet name="header">Primary address</f:facet>
                        <h:outputText value="#{user.address1}"/>
                    </h:column>
                    <!-- ADDR2 -->
                    <h:column id="addr2Col">
                        <f:facet name="header">Secondary address</f:facet>
                        <h:outputText value="#{user.address2}"/>
                    </h:column>
                    <!-- POSTAL CODE -->
                    <h:column id="postalCol">
                        <f:facet name="header">Postal code</f:facet>
                        <h:outputText value="#{user.postalCode}"/>
                    </h:column>
                    <!-- CITY -->
                    <h:column id="cityCol">
                        <f:facet name="header">City</f:facet>
                        <h:outputText value="#{user.city}"/>
                    </h:column>
                    <!-- PROVINCE -->
                    <h:column id="provinceCol">
                        <f:facet name="header">Province</f:facet>
                        <h:outputText value="#{user.province}"/>
                    </h:column>
                    <!-- COMPANY -->
                    <h:column id="companyCol">
                        <f:facet name="header">Company</f:facet>
                        <h:outputText value="#{user.company}"/>
                    </h:column>
                    <!-- HOME PHONE -->
                    <h:column id="homePhoneCol">
                        <f:facet name="header">Home phone</f:facet>
                        <h:outputText value="#{user.homePhone}"/>
                    </h:column>
                    <!-- MOBILE PHONE -->
                    <h:column id="mobilePhoneCol">
                        <f:facet name="header">Mobile phone</f:facet>
                        <h:outputText value="#{user.mobilePhone}"/>
                    </h:column>
                    <!-- TOTAL PURCHASES AMOUNT -->
                    <h:column id="totalPurchasesCol">
                        <f:facet name="header">Total client purchases</f:facet>
                        <h:outputText value="#{user.totalPurchases}"/>
                    </h:column>

                    <!-- EDIT USER BUTTON -->
                    <h:column id="actionCol">
                        <f:facet name="header">Edit client information</f:facet>
                        <h:link styleClass="icon_button icon_button--edit"
                                outcome="/storefront/pages/admin/clientEditor">
                            <f:param name="id" value="#{user.userId}"/>
                        </h:link>
                    </h:column>
                </h:dataTable>
            </h:panelGroup>
        </h:panelGroup>
    </ui:define>
</ui:composition>
</html>

src/main/webapp/storefront/pages/admin/genreEditor.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">>
<ui:composition template="/storefront/templates/managerTemplate.xhtml">
    <ui:define name="metadata">
        <f:metadata>

            <!-- SET THIS PAGE AS ACTIVE -->
            <f:viewAction action="#{navBean.setActivePage('category')}"/>

        </f:metadata>
    </ui:define>
    <ui:define name="content">
        <h:form id="createNewAdForm" styleClass="admin_data__form">
            <h:panelGroup layout="block" styleClass="input">
                <h:outputLabel styleClass="input__label" for="Name" value="Name"/>
                <h:inputText id="Name" styleClass="input__field" value="#{genreEditorBean.name}"/>
            </h:panelGroup>
            
            <h:commandButton styleClass="button button-small button--dark button--small" value="Create Genre"
                             action="#{genreEditorBean.createGenre()}"/>
        </h:form>
    </ui:define>

</ui:composition>
</html>

src/main/webapp/storefront/pages/admin/newsEditor.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">>
<ui:composition template="/storefront/templates/managerTemplate.xhtml">

    <ui:define name="content">
        <h:form id="createNewAdForm" styleClass="admin_data__form">
            <h:panelGroup layout="block" styleClass="input">
                <h:outputLabel styleClass="input__label" for="URL" value="URL"/>
                <h:inputText id="URL" styleClass="input__field" value="#{newsEditorBean.url}"/>
            </h:panelGroup>
            
            <h:commandButton styleClass="button button-small button--dark button--small" value="Create News"
                             action="#{newsEditorBean.createNews()}"/>
        </h:form>
    </ui:define>

</ui:composition>
</html>