src/main/java/com/javaproject/musicbox/entities/Item.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javaproject.musicbox.entities;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

/**
 *
 * @author Danny
 */
@Entity
@Table(name = "item")
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(discriminatorType = DiscriminatorType.STRING, name = "item_type")
public abstract class Item implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "item_id")
    private int itemId;

    @Column(name = "item_type")
    private String itemType;

    @Column(name = "list_price")
    private double listPrice;

    @Column(name = "cost_price")
    private double costPrice;

    @Column(name = "sales_price")
    private double salesPrice;

    @Column(name = "name")
    private String name;

    @Column(name = "picture_path")
    private String picturePath;

    @Column(name = "date_added")
    private Date dateAdded;

    @Column(name = "date_removed")
    private Date dateRemoved;

    @JoinTable(name = "category_item", joinColumns = {
        @JoinColumn(name = "item_id", referencedColumnName = "item_id")}, inverseJoinColumns = {
        @JoinColumn(name = "category_id", referencedColumnName = "category_id")})
    @ManyToMany
    private List<Category> categoryList;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "itemId", fetch = FetchType.EAGER)
    private List<Review> reviewList;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "item")
    private List<OrderItem> orderItems;

    public Item() {
        reviewList = new ArrayList<>();
        orderItems = new ArrayList<>();
        categoryList = new ArrayList<>();
    }

    public Item(int itemId, String itemType) {
        this.itemId = itemId;
        this.itemType = itemType;
    }

    public Item(int itemId, double listPrice, double costPrice, String name, Date dateAdded) {
        this.itemId = itemId;
        this.listPrice = listPrice;
        this.costPrice = costPrice;
        this.name = name;
        this.dateAdded = dateAdded;
    }

    public List<String> getListOf5() {
        List<String> i = new ArrayList<>();
        i.add("1");
        i.add("2");
        i.add("3");
        i.add("4");
        i.add("5");

        return i;
    }

    public int getItemId() {
        return itemId;
    }

    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    public String getItemType() {
        return itemType;
    }

    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    public double getListPrice() {
        return listPrice;
    }

    public void setListPrice(double listPrice) {
        this.listPrice = listPrice;
    }

    public double getCostPrice() {
        return costPrice;
    }

    public void setCostPrice(double costPrice) {
        this.costPrice = costPrice;
    }

    public double getSalePrice() {
        return salesPrice;
    }

    public void setSalePrice(double sp) {
        this.salesPrice = sp;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPicturePath() {
        if(picturePath == null){
            picturePath  = "default.png";
        }
        
        return picturePath;
    }

    public void setPicturePath(String picturePath) {
        if(picturePath == null){
            this.picturePath  = "default.png";
        }
        
        this.picturePath = picturePath;
    }

    public Date getDateAdded() {
        return dateAdded;
    }

    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    public Date getDateRemoved() {
        return dateRemoved;
    }

    public void setDateRemoved(Date dateRemoved) {
        this.dateRemoved = dateRemoved;
    }

    public List<Category> getCategoryList() {
        return categoryList;
    }

    public void setCategoryList(List<Category> categoryList) {
        this.categoryList = categoryList;
    }

    public List<Review> getReviewList() {
        return reviewList;
    }

    public void setReviewList(List<Review> reviewList) {
        this.reviewList = reviewList;
    }

    public int getAverageReview() {
        double total = 0;
        int count = 0;
        for (Review r : getReviewList()) {
            total += (r.getStarRating() * 1.0);
            count++;
        }

        return (int) Math.round(total / count);
    }

    public int getReviewQuantity() {
        return getReviewList().size();
    }

    public void addReview(Review review) {
        reviewList.add(review);
    }

    public List<OrderItem> getOrderItems() {
        return orderItems;
    }

    public void setOrderItems(List<OrderItem> orderItems) {
        this.orderItems = orderItems;
    }

    public void addOrderItem(OrderItem orderItem) {
        this.orderItems.add(orderItem);
    }

    public int countItem() {
        return this.getOrderItems().size();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Item item = (Item) o;
        
        if(!item.name.equals(name)){
            return false;
        }
        
        if(!item.itemType.equals(itemType)){
           return false; 
        }
        
        return true;
    }

    @Override
    public int hashCode() {
        return Objects.hash(itemId);
    }

    @Override
    public String toString() {
        return "Item{"
                + "itemId=" + itemId
                + "itemType=" + itemType
                + ", listPrice=" + listPrice
                + ", costPrice=" + costPrice
                + ", salesPrice=" + salesPrice
                + ", name='" + name + '\''
                + ", picturePath='" + picturePath + '\''
                + ", dateAdded=" + dateAdded
                + ", dateRemoved=" + dateRemoved
                + ", categoryList=" + categoryList
                + ", reviewList=" + reviewList
                + '}';
    }
}

src/main/java/com/javaproject/musicbox/entities/User.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javaproject.musicbox.entities;

import com.javaproject.musicbox.services.admin.ReportsService;
import javax.persistence.*;
import java.io.Serializable;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import javax.inject.Inject;

/**
 * Entity class representing an user
 */
@Entity
@Table(name = "user")
public class User implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id")
    private int userId;

    @Column(name = "fname")
    private String firstName;
    @Column(name = "lname")
    private String lastName;
    private String company ="";
    @Column(name = "address_1")
    private String address1;
    @Column(name = "address_2")
    private String address2 = "";
    private String city;
    private String province;
    @Column(name = "home_phone")
    private String homePhone;
    @Column(name = "cell_phone")
    private String mobilePhone ="";
    @Column(name = "postal_code")
    private String postalCode;
    private String email;
    private byte[] hash;
    private String salt;
    @Column(name = "is_manager")
    private boolean isManager;


    @JoinColumn(name = "last_visited_category", referencedColumnName = "category_id")
    @OneToOne
    private Category lastVisitedCategory;

    @JoinColumn(name = "user_id", referencedColumnName = "user_id")
    @OneToMany(cascade = CascadeType.PERSIST)
    private List<Answer> answers;

    @OneToMany(mappedBy = "user", cascade = CascadeType.PERSIST)
    private List<Order> orders;

    @OneToOne(mappedBy = "user", cascade = CascadeType.PERSIST)
    private ShoppingCart shoppingCart;

    @Transient
    private String password;

    @Transient
    private double totalPurchases;

    public User() {
    }

    public User(int userId) {
        this.userId = userId;
    }

    public User(String firstName, String lastName, String company, String address1, String address2, String city, String province, String homePhone, String mobilePhone, String postalCode, String email, byte[] hash, String salt, Category lastVisitedCategory, List<Answer> answers, List<Order> orders, String password, double totalPurchases) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.company = company;
        this.address1 = address1;
        this.address2 = address2;
        this.city = city;
        this.province = province;
        this.homePhone = homePhone;
        this.mobilePhone = mobilePhone;
        this.postalCode = postalCode;
        this.email = email;
        this.hash = hash;
        this.salt = salt;
        this.lastVisitedCategory = lastVisitedCategory;
        this.answers = answers;
        this.orders = orders;
        this.password = password;
        this.totalPurchases = totalPurchases;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getAddress1() {
        return address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getHomePhone() {
        return homePhone;
    }

    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }

    public String getMobilePhone() {
        return mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode.trim().replaceAll(" ", "");
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public byte[] getHash() {
        return hash;
    }

    public void setHash(byte[] hash) {
        this.hash = hash;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public Category getLastVisitedCategory() {
        return lastVisitedCategory;
    }

    public void setLastVisitedCategory(Category lastVisitedCategory) {
        this.lastVisitedCategory = lastVisitedCategory;
    }

    public boolean isManager() {
        return isManager;
    }

    public void setManager(boolean manager) {
        isManager = manager;
    }

    public List<Answer> getAnswers() {
        return answers;
    }

    public void setAnswer(List<Answer> answer) {
        this.answers = answer;
    }

    public List<Order> getOrders() {
        return orders;
    }

    public void setOrders(List<Order> orders) {
        this.orders = orders;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public ShoppingCart getShoppingCart() {
        return shoppingCart;
    }

    public void setShoppingCart(ShoppingCart shoppingCart) {
        this.shoppingCart = shoppingCart;
    }
    
     /**
     * Get the total amount of money the user payed for all the items per user
     *
     * @return
     */
    public double getTotalUserPayed() {
        double sum = 0 ;
        for(Order o : this.orders){
            //for each order add the sum
            sum+= o.getGrandTotal();
                
            }
        return Math.round(sum * 100.0) / 100.0;
        }
   
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return userId == user.userId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(userId);
    }

    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", company='" + company + '\'' +
                ", address1='" + address1 + '\'' +
                ", address2='" + address2 + '\'' +
                ", city='" + city + '\'' +
                ", province='" + province + '\'' +
                ", homePhone='" + homePhone + '\'' +
                ", mobilePhone='" + mobilePhone + '\'' +
                ", postalCode='" + postalCode + '\'' +
                ", email='" + email + '\'' +
                ", hash=" + Arrays.toString(hash) +
                ", salt='" + salt + '\'' +
                ", lastVisitedCategory=" + lastVisitedCategory +
                ", answer=" + answers +
                ", orders=" + orders +
                ", password='" + password + '\'' +
                ", isManager='" + isManager + '\'' +
                ", totalPurchases='" + totalPurchases + '\'' +
                '}';
    }

    public double getTotalPurchases() {
        return totalPurchases;
    }

    public void setTotalPurchases(double totalPurchases) {
        this.totalPurchases = totalPurchases;
    }
}

src/main/webapp/storefront/pages/admin/reportComponents/salesPerAlbum.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">
    <ui:composition>
        <ui:define name="metadata">
            <h:outputStylesheet name="css/pages/admin/admin_page.css" />
        </ui:define>

        <!-- Choose An Artist -->
        <h:form class="forms-margin" id="chooseAlbumForm">
            <h:selectOneMenu  class="padding-horizontal add-review-stars" value="#{reportsBean.albumId}">
                <f:selectItems value="#{reportsBean.getAllItems('album')}" var="album"
                               itemLabel="#{album.name}" itemValue="#{album.itemId}" />
                <f:ajax listener="#{reportsBean.submitAlbum()}" execute="@this" render="@form" />
            </h:selectOneMenu>
            
        <!-- Show All Sales For Chosen Album -->
        <h:panelGroup  class ="vertical-flex margin-top" rendered ="#{not empty reportsBean.allAlbumOrders}">

            <!-- Total Sales For Album -->
            <h:outputText value="#{msg.totalSales}: #{reportsBean.totalSalesPerAlbum()} $"/> 

            <h:dataTable styleClass="dataTable hover stripe order-column row-border"
                         value="#{reportsBean.allAlbumOrders}"
                         var="orderItem">

                <!-- Order ID -->
                <h:column>
                    <f:facet name="header">#{msg.order}</f:facet>
                    <h:outputText value="#{orderItem.order.orderId}"/>
                </h:column>

                <!-- Date Of Order -->
                <h:column>
                    <f:facet name="header">#{msg.date}</f:facet>
                    <h:outputText value="#{orderItem.order.timestamp}"/>
                </h:column>

                <!-- Bought For -->
                <h:column>
                    <f:facet name="header">#{msg.boughtFor}</f:facet>
                    <h:outputText value="#{reportsBean.album.listPrice - reportsBean.album.salePrice}$ (#{msg.originalPrice}: #{reportsBean.album.listPrice}$)"/>
                </h:column>
            </h:dataTable>
        </h:panelGroup>
        
        <!-- Album Not Sold Yet -->
        <h:panelGroup  class ="vertical-flex margin-top" rendered ="#{empty reportsBean.allAlbumOrders}">
            <h:outputText value="#{msg.albumNotSold}"/>
        </h:panelGroup>
        </h:form>

    </ui:composition>
</html>

src/main/webapp/storefront/pages/admin/reportComponents/salesPerArtist.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">
    <ui:composition>
        <ui:define name="metadata">
            <h:outputStylesheet name="css/pages/admin/admin_page.css" />
        </ui:define>

        <!-- Choose An Artist -->
        <h:form class="forms-margin" id="chooseArtistForm">
            <h:selectOneMenu  class="padding-horizontal add-review-stars" value="#{reportsBean.artistId}">
                <f:selectItems value="#{reportsBean.artists}" var="artist"
                               itemLabel="#{artist.name}" itemValue="#{artist.artistId}" />
                <f:ajax listener="#{reportsBean.submitArtist()}" execute="@this" render="@form" />
            </h:selectOneMenu>

        <!-- Total Payed Per Albums and Tracks-->
        <h1 class="artist-sales">#{msg.totalSales}  - #{reportsBean.totalPayedArtistAlbum() + reportsBean.totalPayedArtistTrack()}$</h1>

        <!-- Show Total Sales Of Albums .. if any -->            
        <h:panelGroup  id="artist-sales-items" class ="vertical-flex margin-top" rendered ="#{not empty reportsBean.artist.albumCollection}">
       
            <!-- Total Payed Per Albums-->
            <h2>#{msg.album} - #{msg.totalSales}: #{reportsBean.totalPayedArtistAlbum()}$</h2>

            <h:dataTable styleClass="dataTable hover stripe order-column row-border"
                         value="#{reportsBean.artist.albumCollection}"
                         var="album">

                <!-- Item Name -->
                <h:column>
                    <f:facet name="header">#{msg.item}</f:facet>
                    <h:link class="link hover-effect display-block margin-top" value="#{album.name}"
                            outcome="/storefront/pages/public/itemDetails?id=#{album.itemId}"/>
                </h:column>

                <!-- Item Price -->
                <h:column>
                    <f:facet name="header">#{msg.price}</f:facet>
                    <h:outputText value="#{album.listPrice}$"/>
                </h:column>

                <!-- Total Sold Of That Item -->
                <h:column>
                    <f:facet name="header">#{msg.totalSales}</f:facet>
                    <h:outputText value="#{reportsBean.countItem(album)}"/>
                </h:column>

            </h:dataTable>
        </h:panelGroup>

        <!-- Show Total Sales Of Tracks -->            
        <h:panelGroup  class ="vertical-flex margin-top">

            <!-- Total Payed Per Tracks -->
            <h2>#{msg.track} - #{msg.totalSales}: #{reportsBean.totalPayedArtistTrack()}$</h2>

            <h:dataTable styleClass="dataTable hover stripe order-column row-border"
                         value="#{reportsBean.artist.trackCollection}"
                         var="track">

                <!-- Item Name -->
                <h:column>
                    <f:facet name="header">#{msg.item}</f:facet>
                    <h:link class="link hover-effect display-block margin-top" value="#{track.name}"
                            outcome="/storefront/pages/public/itemDetails?id=#{track.itemId}"/>
                </h:column>

                <!-- Item Price -->
                <h:column>
                    <f:facet name="header">#{msg.price}</f:facet>
                    <h:outputText value="#{track.listPrice}$"/>
                </h:column>

                <!-- Total Sold Of That Item -->
                <h:column>
                    <f:facet name="header">#{msg.totalSales}</f:facet>
                    <h:outputText value="#{reportsBean.countItem(track)}"/>
                </h:column>

            </h:dataTable>
        </h:panelGroup>
        
        </h:form>

    </ui:composition>
</html>

src/main/webapp/storefront/pages/admin/reportComponents/salesPerTrack.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">
    <ui:composition>
        <ui:define name="metadata">
            <h:outputStylesheet name="css/pages/admin/admin_page.css" />
        </ui:define>

        <!-- Choose An Artist -->
        <h:form class="forms-margin" id="chooseTrackForm">
            <h:selectOneMenu  class="padding-horizontal add-review-stars" value="#{reportsBean.trackId}">
                <f:selectItems value="#{reportsBean.getAllItems('track')}" var="track"
                               itemLabel="#{track.name}" itemValue="#{track.itemId}" />
                <f:ajax listener="#{reportsBean.submitTrack()}" execute="@this" render="@form" />
            </h:selectOneMenu>

  
            <!-- Show All Sales For Track.. if any -->
            <h:panelGroup  class ="vertical-flex margin-top" rendered ="#{not empty reportsBean.allTrackOrders}">

                <!-- Total Sales Per Track -->
                <h:outputText value="#{msg.totalSales}: #{reportsBean.totalSalesPerTrack()} $"/> 

                <h:dataTable styleClass="dataTable hover stripe order-column row-border"
                             value="#{reportsBean.allTrackOrders}"
                             var="orderItem">

                    <!-- Order ID -->
                    <h:column>
                        <f:facet name="header">#{msg.order}</f:facet>
                        <h:outputText value="#{orderItem.order.orderId}"/>
                    </h:column>

                    <!-- Date Ordered -->
                    <h:column>
                        <f:facet name="header">#{msg.date}</f:facet>
                        <h:outputText value="#{orderItem.order.timestamp}"/>
                    </h:column>

                    <!-- Bought For -->
                    <h:column>
                        <f:facet name="header">#{msg.boughtFor}</f:facet>
                        <h:outputText value="#{reportsBean.track.listPrice - reportsBean.track.salePrice}$ (#{msg.originalPrice}: #{reportsBean.track.listPrice}$)"/>
                    </h:column>

                </h:dataTable>
            </h:panelGroup>
            
            <!-- Track Not Sold Yet -->
            <h:panelGroup  class ="vertical-flex margin-top" rendered ="#{empty reportsBean.allTrackOrders}">
                <h:outputText value="#{msg.trackNotSold}"/>
            </h:panelGroup>
        </h:form>
   </ui:composition>
</html>

src/main/webapp/storefront/pages/admin/reportComponents/salesPerUser.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">
    <ui:composition>
        <ui:define name="metadata">
            <h:outputStylesheet name="css/pages/admin/admin_page.css" />
        </ui:define>

        <!-- Choose An Artist -->
        <h:form class="forms-margin" id="chooseUserForm">
            <h:selectOneMenu  class="padding-horizontal add-review-stars" value="#{reportsBean.clientId}">
  <f:selectItems value="#{reportsBean.users}" var="user"  
                               itemLabel="#{user.firstName} #{user.lastName} - ID: #{user.userId}" itemValue="#{user.userId}" />
                <f:ajax listener="#{reportsBean.submitClient()}" execute="@this" render="@form" />
            </h:selectOneMenu>

        
            <!-- Show All Items User Bought -->
            <h:panelGroup  class ="vertical-flex margin-top" id="user-sales" rendered ="#{not empty reportsBean.userItems}">

                <!-- Total Payed in $ -->
                <h:outputText value="#{msg.totalSalesPerUser} #{reportsBean.user.firstName}: #{reportsBean.totalUserPayed}$ "/>

                <!-- Show Items User Bought -->
                <h:dataTable styleClass="dataTable hover stripe order-column row-border"
                             value="#{reportsBean.userItems}"
                             var="item">

                    <!-- Item Name -->
                    <h:column>
                        <f:facet name="header">#{msg.item}</f:facet>
                        <h:link class="link hover-effect display-block margin-top" value="#{item.name}"
                                outcome="/storefront/pages/public/itemDetails?id=#{item.itemId}"/>
                    </h:column>

                    <!-- Item Type -->
                    <h:column>
                        <f:facet name="header">#{msg.type}</f:facet>
                        <h:outputText value="#{item.itemType}"/>
                    </h:column>

                    <!-- Item Price -->
                    <h:column>
                        <f:facet name="header">#{msg.price}</f:facet>
                        <h:outputText value="#{item.listPrice}$"/>
                    </h:column>

                </h:dataTable>
            </h:panelGroup>

            <!-- User Did Not Make Any Sale Yet-->
            <h:panelGroup class ="vertical-flex margin-top" rendered ="#{empty reportsBean.userItems}">
                <h:outputText value="#{msg.userDidntBuy}"/>
            </h:panelGroup>
        </h:form>

    </ui:composition>
</html>

src/main/webapp/storefront/pages/admin/reportComponents/topUserSellers.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">
    <ui:composition>
        <ui:define name="metadata">
            <h:outputStylesheet name="css/pages/admin/admin_page.css" />
        </ui:define>
        <ui:repeat value="#{reportsBean.topSellerUsers}" var ="user">
            <div class="flex-horizontal text-margin-horizontal">
                <h:outputText value=" - #{user.firstName} #{user.lastName} - #{msg.totalSales}: #{user.totalUserPayed}"/>
            </div>
        </ui:repeat>
    </ui:composition>
</html>